// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdD8g0pRUz-Ls_wBbiarFwzOhcwefXWMs',
    appId: '1:268360127074:web:b9a062ac3cf2b6dd9eb73b',
    messagingSenderId: '268360127074',
    projectId: 'b-social-af08a',
    authDomain: 'b-social-af08a.firebaseapp.com',
    storageBucket: 'b-social-af08a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_rpyVmiUNfmj0NJSZ6lARdv58JuVJHK0',
    appId: '1:268360127074:android:faf2dc52128537ef9eb73b',
    messagingSenderId: '268360127074',
    projectId: 'b-social-af08a',
    storageBucket: 'b-social-af08a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6IKxviEcScXgjF6VY0_MjWppJdEDUYGU',
    appId: '1:268360127074:ios:430ec18740d2dfab9eb73b',
    messagingSenderId: '268360127074',
    projectId: 'b-social-af08a',
    storageBucket: 'b-social-af08a.appspot.com',
    iosClientId: '268360127074-oo6hfhkdj48tn1ot1ui502b4opk0stcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6IKxviEcScXgjF6VY0_MjWppJdEDUYGU',
    appId: '1:268360127074:ios:49d4f501942ebdb19eb73b',
    messagingSenderId: '268360127074',
    projectId: 'b-social-af08a',
    storageBucket: 'b-social-af08a.appspot.com',
    iosClientId: '268360127074-cqj3cm6glsgt2hfnj0ea3aum70ljig77.apps.googleusercontent.com',
    iosBundleId: 'com.example.bSocial.RunnerTests',
  );
}
